name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Set up Gradle 7.6
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: '7.6'

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Upload mod .jar
      uses: actions/upload-artifact@v4
      with:
        name: moonHueInjector-jar
        path: build/libs/*.jar